### PR TITLE
New design for navbar/header

### PR DESCRIPTION
**Pull request by DementevVV**
I made a new design 4 navbar, header and footer. 
imho black color scheme is better than white.
Made test in Firefox and Chrome.

### CODE REVIEW

**Comment by KSkobeltsynStudio** [comment]
Cool, but diff is minimal lol

**Comment by DementevVV** [comment]
we're working on it :D
this is the beginning

**Comment by KSkobeltsynStudio** [comment]
I have access to Unreal Engine 4 sources yo

**Comment by DementevVV** [comment]
\m/
I want to see live!

**Pull request merged**
